services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
#    networks:
#      - spring
#  notification:
#    image: elmojke/notification:latest
#    container_name: notification
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - rabbitmq
#networks:
#  spring:
#    driver: bridge
