spring:
  rabbitmq:
    addresses: localhost:5672
  h2:
    console:
      enabled: true
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:notification
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key


